2024-09-13 11:53:11,829 ERROR: Exception on / [GET] [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/routes.py", line 27, in index
    return render_template('index.html',title='Home', posts=posts, form=form)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/templates/index.html", line 19, in block 'content'
    {% include "_post.hmtl" %}
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.hmtl
2024-09-13 11:53:38,235 INFO: Microblog startup [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/__init__.py:43]
2024-09-13 12:08:36,184 INFO: Microblog startup [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/__init__.py:43]
2024-09-13 12:08:38,913 ERROR: Exception on /index [GET] [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/routes.py", line 27, in index
    posts = current_user.followed_posts().paginate(
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2024-09-13 12:08:40,291 ERROR: Exception on /index [GET] [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/routes.py", line 27, in index
    posts = current_user.followed_posts().paginate(
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2024-09-13 12:10:32,292 INFO: Microblog startup [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/__init__.py:43]
2024-09-13 12:10:36,425 ERROR: Exception on / [GET] [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/routes.py", line 27, in index
    posts = current_user.followed_posts().paginate(
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2024-09-13 12:12:48,564 INFO: Microblog startup [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/__init__.py:43]
2024-09-13 12:13:08,141 INFO: Microblog startup [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/__init__.py:43]
2024-09-13 12:13:10,688 ERROR: Exception on / [GET] [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/routes.py", line 27, in index
    posts = current_user.followed_posts().paginate(
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2024-09-13 12:15:30,076 INFO: Microblog startup [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/__init__.py:43]
2024-09-13 12:17:20,313 INFO: Microblog startup [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/__init__.py:43]
2024-09-13 12:26:06,575 INFO: Microblog startup [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/__init__.py:43]
2024-09-13 12:34:59,199 INFO: Microblog startup [in /home/user/Documentos/FP_HBTN_Microblog/flaskyblog/app/__init__.py:43]
